Repository canonical/maas.io, pull requests merged in 2018-11, with the labels that each got.

#284 Add margin between submit button and list in contact-us page
  templates/contact-us.html
Labels: Review: Code +1, Review: QA +1

#283 Update how-it-works page to Vanilla 1.8 + update copy
  static/sass/main.scss
  templates/how-it-works.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#285 Update tour page copy and fix Vanilla 1.8 regressions
  static/sass/_patterns_takeunders.scss
  static/sass/main.scss
  templates/tour.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#289 Discourse link navigation
  static/sass/_patterns_navigation.scss
  templates/includes/header.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#290 Generate GA Events on link clicks and form submits
  static/js/ga.js
  templates/base_index.html
Labels: Review: Code +1, Review: QA +1
