Repository canonical/maas.io, pull requests merged in 2018-12, with the labels that each got.

#295 Add the KVM feature to the tour
  templates/tour.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#296 Content updates to the homepage
  templates/how-it-works.html
  templates/index.html
  templates/tour.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#298 Fix the release-notes link on the tour page
  templates/tour.html
Labels: Review: Code +1, Review: QA +1

#299 Use canonicalwebteam.django_views for template finder
  redirects.yaml
  requirements.txt
  webapp/views.py
Labels: Review: Code +1, Review: QA +1
