Repository canonical/maas.io, pull requests merged in 2018-05, with the labels that each got.

#238 Update insights links
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Status: Review

#239 Update for GDPR
  templates/contact-us.html
Labels: Don't merge, Review: Code +1, Review: QA +1, Review: UX +1

#248 Stop heading from wrapping
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#247 Update copy and links to MAAS 2.4 and Ubuntu 18.04
  templates/install.html
Labels: Review: Code +1, Review: QA +1

#250 2.4 - header wrapping fix and install page updates
  templates/index.html
  templates/install.html
Labels: Review: Code +1, Review: QA +1
