Repository canonical/maas.io, pull requests merged in 2019-03, with the labels that each got.

#312 Added google site verification snippet
  templates/includes/head.html
Labels: Review: Code +1

#314 Fix the error pages, fix the app
  templates/404.html
  templates/500.html
  webapp/urls.py
  webapp/views.py
Labels: Review: Code +1, Review: QA +1

#317 Switch to synchronous workers
  entrypoint
Labels: Review: Code +1, Review: QA +1

#318 Disable Google Optimize page hiding
  templates/includes/tag_manager.html
Labels: Review: Code +1, Review: QA +1

#310 Update the homepage based on the copy doc
  templates/index.html
Labels: Don't merge, Review: Design needed, Review: UX needed

#321 change hero background image; hide video on mobile
  static/sass/_patterns_strips.scss
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#322 ensure copy matches doc; apply consistent spelling of bare-metal
  templates/includes/footer.html
  templates/index.html
Labels: Review: QA +1
