Repository canonical/maas.io, pull requests merged in 2019-07, with the labels that each got.

#348 Upgrade docs module
  requirements.txt
Labels: Review: Code needed, Review: QA needed

#351 MAAS docs template tidy up
  static/sass/_patterns_docs.scss
  templates/docs.html
Labels: Review: Code +1, Review: QA +1

#349 Redirects to handle docs.maas.io URLs
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#354 Add searchbar to docs pages
  templates/docs.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#353 Create docs/api page manually
  static/sass/_patterns_docs.scss
  templates/docs/api.html
  templates/docs/document.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#363 Remove image versions from pricing table
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#357 Fix modal contact us with grecaptcha, design, questions
  static/js/dynamic-contact-form.js
  static/js/dynamic-contact-form2.js
  templates/base_index.html
  templates/includes/_contact-us.html
  templates/includes/_form-validation.html
Labels: Review: Code +1, Review: QA +1

#346 Maas docs
  Dockerfile
  redirects.yaml
  requirements.txt
  static/js/highlight.pack.js
  static/sass/_hljs.scss
  static/sass/_layout_docs.scss
  static/sass/_patterns_sidenav.scss
  static/sass/main.scss
  templates/base_index.html
  templates/docs/api.html
  templates/docs/document.html
  templates/docs/search.html
  templates/includes/footer.html
  templates/includes/header.html
  webapp/app.py
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#368 Add search and is-active to /docs/api
  templates/docs/api.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#371 Use discourse-docs v0.6.2 to get /docs/sitemap.txt
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#372 discourse-docs v0.6.4 for domain in /docs/sitemap.txt
  requirements.txt
Labels: Review: Code +1, Review: QA +1

#374 Highlight /docs in search results too
  redirects.yaml
  templates/includes/header.html
Labels: Review: Code +1, Review: QA +1
