Repository canonical/maas.io, pull requests merged in 2019-08, with the labels that each got.

#376 Fix redirect to old docs
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#373 Create the VMWare image download page which will be linked from the docs
  templates/includes/_form-validation.html
  templates/vmware-images.html
Labels: Review: Code +1, Review: QA +1

#377 fix broken mobile classes
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#379 Fix the news feed RSS URL
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#382 Remove close button from the vmware-images page
  templates/vmware-images.html
Labels: Review: Code +1

#381 Add homepage footer
  templates/index.html
Labels: Review: UX +1

#384 Update forum to discourse
  templates/includes/header.html
Labels: Review: Code +1

#386 Layout the three audiences section
  static/sass/main.scss
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1
