Repository canonical/maas.io, pull requests merged in 2019-06, with the labels that each got.

#337 Update any os on any hardware graph
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#336 Update homepage content
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#338 HP pricing table: styling and copy fixes
  static/sass/_patterns_tables.scss
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#333 Move app to Flask
  .bzrignore
  .env
  .gitignore
  README.md
  entrypoint
  manage.py
  requirements.txt
  templates/404.html
  templates/500.html
  templates/base_index.html
  templates/contact-us.html
  templates/how-it-works.html
  templates/includes/_contact-us.html
  templates/includes/footer.html
  templates/includes/head.html
  templates/index.html
  templates/install.html
  templates/thank-you.html
  templates/tour.html
  webapp/app.py
  webapp/feeds.py
  webapp/settings.py
  webapp/templatetags/__init__.py
  webapp/templatetags/utils.py
  webapp/urls.py
  webapp/views.py
  webapp/wsgi.py
Labels: Review: Code +1, Review: QA +1

#342 Add discourse module to project + set up basic templates
  redirects.yaml
  requirements.txt
  static/js/highlight.pack.js
  static/sass/_hljs.scss
  static/sass/_patterns_docs.scss
  static/sass/_patterns_navigation.scss
  static/sass/_settings_colors.scss
  static/sass/main.scss
  templates/docs.html
  templates/includes/footer.html
  templates/includes/header.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#343 Update site to 2.6 release
  templates/install.html
  templates/tour.html
Labels: Review: Code +1

#344 Add search to docs
  templates/search.html
  webapp/app.py
  webapp/search.py
Labels: Review: Code +1
