Repository canonical/maas.io, pull requests merged in 2020-01, with the labels that each got.

#421 Change Google Tag Manager
  templates/includes/tag_manager.html
Labels: Review: Code +1, Review: QA +1

#418 Move blog feed from server to client
  static/js/latest-news.js
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#417 Surify maas.io homepage banner
  static/sass/_patterns_sidenav.scss
  static/sass/_patterns_strips.scss
  static/sass/main.scss
  templates/contact-us.html
  templates/docs/api.html
  templates/docs/document.html
  templates/how-it-works.html
  templates/index.html
  templates/install.html
  templates/tour.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#424 Float the improve the doc link on the docs
  static/sass/_layout_docs.scss
  templates/docs/document.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#428 Change link in footer
  templates/includes/footer.html
Labels: Review: Code +1

#431 Fix malformed GA event handlers.
  templates/contact-us.html
  templates/includes/header.html
  templates/index.html
  templates/install.html
  templates/tour.html
Labels: Review: Code +1

#433 Fix gallery images
  templates/install.html
  templates/tour.html
Labels: Review: Code +1, Review: QA +1

#435 Add missing </section>
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#436 Remove stray s
  templates/index.html
Labels: Review: Code +1
