Repository canonical/maas.io, pull requests merged in 2020-09, with the labels that each got.

#518 Only load all the YouTube scripts when the user watches a video
  templates/index.html
Labels: Review: Code needed, Review: QA needed

#519 Fix the get in touch tracking
  static/js/dynamic-contact-form.js
Labels: Review: Code +1

#520 Fix links from the tour to docs
  templates/tour.html
Labels: Review: Code +1, Review: QA +1

#521 Add link to open job role
  templates/includes/footer.html
Labels: Review: Code +1

#523 Update install instructions
  templates/install.html
Labels: Review: Code +1

#528 Fix installation of python linters
  .github/workflows/pr.yaml
Labels: Review: Code +1

#529 Remove category hardcoded
  .env
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#525 Remove the copydoc meta tag from docs
  templates/base_index.html
  templates/docs/document.html
Labels: Review: Code +1 (with changes)

#526 Update homepage to latest copydoc.
  templates/index.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1, Review: UX +1

#527 Fix malformed external link classes
  templates/thank-you.html
Labels: Review: Code +1, Review: QA +1

#530 Use webteam default renovate config
  renovate.json
Labels: Review: Code +1
