Repository canonical/maas.io, pull requests merged in 2020-02, with the labels that each got.

#429 Use multi-stage builds with Ubuntu Focal
  .dockerignore
  Dockerfile
  package.json
Labels: Review: Code +1, Review: QA +1

#438 Pin discourse-docs at 0.6.5 due to version 0.10.X breaking
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#439 Fix typo in error page
  templates/500.html
Labels: Review: Code needed

#440 Bump discourse docs version
  requirements.txt
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#441 Add tutorials
  requirements.txt
  static/js/modules/global-nav/global-nav.js
  static/sass/_patterns_tutorials.scss
  static/sass/main.scss
  templates/includes/header.html
  templates/tutorials/index.html
  templates/tutorials/tutorial.html
  webapp/app.py
Labels: Review: Code +1, Review: QA +1

#446 Update footer and divider for tutorials
  templates/includes/footer.html
  templates/tutorials/index.html
Labels: Review: Code +1, Review: QA +1

#449 Update install instructions to use the snap for 2.7
  templates/install.html
Labels: Review: Code +1

#447 Use British spelling for the word “centre”
  templates/index.html
Labels: Review: Code +1

#454 Handle redirects in discourse
  redirects.yaml
Labels: Review: Code +1, Review: QA +1

#451 Build release banner for 2.7.
  templates/base_index.html
  templates/includes/banner.html
Labels: Review: Code +1 (with changes), Review: QA +1, Review: UX +1

#450 Support flexible python versions
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#455 Fix dockerfile by hardcoding python 3.8
  Dockerfile
Labels: Review: Code +1, Review: QA +1

#456 Update Greenhouse link to point to live job post
  templates/includes/footer.html
Labels: Review: Code +1, Review: QA +1

#457 Update support information in the footer
  templates/includes/footer.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1
