Repository canonical/maas.io, pull requests merged in 2020-03, with the labels that each got.

#459 Update title to MAAS 2.7 from MAAS 2.6
  templates/tour.html
Labels: Review: Code +1

#464 Revert logos to previous loading method
  templates/index.html
Labels: Review: Code +1, Review: QA +1

#467 Replace sass-lint with stylelint
  .sass-lint.yml
  .stylelintrc
  package.json
  static/sass/_layout_docs.scss
  static/sass/_patterns_hero-video.scss
  static/sass/_patterns_lists.scss
  static/sass/_patterns_modal.scss
  static/sass/_patterns_sidenav.scss
  static/sass/_patterns_strips.scss
  static/sass/_patterns_takeunders.scss
  static/sass/_patterns_tutorials.scss
  static/sass/main.scss
  yarn.lock
Labels: Review: Code +1 (with changes), Review: QA +1

#465 Update packer-maas to 1.0.3
  templates/vmware-images.html
Labels: Review: Code +1, Review: QA +1
