Repository canonical/maas.io, pull requests merged in 2020-06, with the labels that each got.

#489 “Setup” > “Set up”
  templates/install.html
Labels: Review: Code +1

#493 GitHub actions
  .circleci/config.yml
  .github/workflows/pr.yaml
  package.json
Labels: Review: Code +1, Review: QA +1

#496 Add k8s configuration in deploy/site.yaml
  README.md
  deploy/site.yaml
Labels: Review: Code +1

#497 Manually update the API docs with 2.8
  templates/docs/api.html
Labels: Don't merge, Review: QA +1

#499 Add 2.8 release banner
  templates/index.html
Labels: Review: Code +1, Review: QA +1, Review: UX +1

#502 Add redirect for legacy to homepage
  redirects.yaml
Labels: Review: Code +1, Review: QA +1
