Repository canonical/maas.io, pull requests merged in 2021-09, with the labels that each got.

#605 Update the social meta image
  templates/includes/head.html
Labels: Review: QA +1, Review: Code +1

#606 Improve the social banner
  templates/includes/head.html
Labels: Review: QA +1, Review: Code +1

#608 Run link checks daily
  .github/workflows/docs-links.yaml
Labels: Review: Code +1

#609 Increase the timeout when linkchecking
  .github/workflows/docs-links.yaml
Labels: Review: Code needed

#610 Allow linkchecking on demand
  .github/workflows/docs-links.yaml
Labels: Review: Code +1

#611 Move linkchecker config to file
  .github/workflows/docs-links.yaml
Labels: Review: Code +1

#612 [docs-links] Remove trailing "
  .github/workflows/docs-links.yaml
Labels: Review: Code +1

#614 Increase the timeouts from the default to 120 seconds
  entrypoint
Labels: Review: QA +1, Review: Code +1
