Repository canonical/maas.io, pull requests merged in 2021-12, with the labels that each got.

#649 Fix MAAS logo misalignement in Safari
  templates/includes/header.html
Labels: Review: QA +1, Review: Code +1

#648 Add MAAS 3.1 banner
  templates/base_index.html
  templates/includes/banner.html
  templates/includes/header.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1 (with changes)

#650 Build resources page
  package.json
  templates/includes/header.html
  templates/resources.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1, Review: UX +1

#651 Update resources.html
  templates/resources.html
Labels: Review: Code needed

#657 update enterprise section copy
  templates/index.html
Labels: Review: QA +1, Review: Code +1

#656 Add new link to hero banner
  templates/index.html
Labels: Review: QA +1, Review: Code +1

#660 remove latest news section
  templates/index.html
Labels: Review: QA needed, Review: Code needed

#662 Add bare metal K8s whitepaper to /resources, fix video link
  templates/resources.html
Labels: Review: Code +1 (with changes)

#665 Update development steps
  README.md
Labels: Review: Code +1

#664 Update resources.html (#3)
  templates/resources.html
Labels: Review: Code +1

#666 use custom video youtube iframe
  static/sass/_patterns_hero-video.scss
  static/sass/main.scss
  templates/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1
