Repository canonical/maas.io, pull requests merged in 2021-11, with the labels that each got.

#632 Reduce the requests per second in docs linkchecker
  scripts/linkcheckerrc
Labels: Review: Code +1

#633 Reduce treads in docs linkchecker
  scripts/linkcheckerrc
Labels: Review: Code +1

#634 Disable docs linkchecker cron job
  .github/workflows/docs-links.yaml
Labels: Review: Code +1

#624 Update version on /tour
  templates/tour.html
Labels: Review: QA +1, Review: Code +1

#637 Improve docs performance
  requirements.txt
  webapp/app.py
  webapp/doc_parser.py
Labels: Don't merge

#642 Embed the youtube video instead of the subtle image
  static/sass/_patterns_hero-video.scss
  static/sass/main.scss
  templates/index.html
Labels: Review: QA +1, Review: Design +1, Review: Code +1

#645 Revert "Embed the youtube video instead of the subtle image"
  static/sass/_patterns_hero-video.scss
  static/sass/main.scss
  templates/index.html
Labels: Review: QA +1

#643 Add the local blog system to the site
  requirements.txt
  static/sass/_patterns_cards.scss
  static/sass/main.scss
  templates/base_index.html
  templates/blog/article.html
  templates/blog/index.html
  templates/blog/partials/_blog-card.html
  templates/blog/partials/_blog-card_aside.html
  templates/blog/partials/_blog-card_featured.html
  templates/includes/head.html
  templates/includes/header.html
  templates/index.html
  webapp/app.py
  webapp/blog/__init__.py
  webapp/blog/views.py
Labels: Review: QA +1, Review: Design +1, Review: Code +1
