Repository canonical/maas.io, pull requests merged in 2022-02, with the labels that each got.

#687 Don't double parse the index topic
  webapp/doc_parser.py
Labels: Review: QA +1, Review: Code +1

#688 Speedups
  tests/test_doc_parser.py
  webapp/doc_parser.py
Labels: Review: QA +1, Review: Code +1, python

#689 Improve meta values via template inheritance
  templates/base_index.html
  templates/docs/document.html
  templates/includes/head.html
Labels: Review: QA +1, Review: Code +1

#690 Update redirects.yaml
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#695 use single contact form
  static/js/dynamic-contact-form.js
  templates/base_index.html
  templates/contact-us.html
  templates/includes/contact-us.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#697 update vanilla to 2.37.1
  package.json
  yarn.lock
Labels: Review: Code +1

#696 remove jQuery scripts
  package.json
  static/js/jquery.command-line.js
  static/js/jquery.modal.min.js
  static/sass/_patterns_modal.scss
  templates/base_index.html
  templates/tour.html
  yarn.lock
Labels: Review: QA +1, Review: Code +1

#702 Update canonicalUpdatesOptIn value
  templates/contact-us.html
Labels: Review: QA +1, Review: Code +1

#705 Remove circleci badge from readme
  README.md
Labels: Review: Code +1

#707 Mark cchardet as optional for `aarch64`
  requirements.txt
Labels: Review: Code +1, python

#708 Fix small accumulated redirect errors
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#710 More speedups of doc workflow
  webapp/doc_parser.py
Labels: Review: Code needed, python
