Repository canonical/maas.io, pull requests merged in 2023-05, with the labels that each got.

#781 Rename UA to Pro
  templates/contact-us.html
  templates/index.html
  templates/support.html
  templates/thank-you.html
  templates/tour.html
Labels: Review: Code +1

#784 Update redirects.yaml
  redirects.yaml
Labels: Review: QA +1, Review: Code +1

#785 Fix sidebar navigation for api
  templates/docs/api.html
  templates/docs/document.html
Labels: Review: QA +1, Review: Code +1 (with changes)

#787 Renovate/major internal
  static/js/navigation.js
  static/sass/main.scss
  templates/base_index.html
  templates/includes/footer.html
  templates/includes/header.html
Labels: Review: QA +1, Review: Code +1
